# Importing Dependencies

In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler # standarize the data to a common range
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

# Data collection and Analysis

*PIMA Diabetes Dataset*

1- loading the diabetes dataset to a pandas dataframe

In [3]:
diabetes_dataset = pd.read_csv('diabetes.csv')

In [4]:
diabetes_dataset.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [5]:
#number of rows and collumns
diabetes_dataset.shape

(768, 9)

In [6]:
#statistical measures of the data 
diabetes_dataset.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [9]:
diabetes_dataset['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

we notice that the number of diabetic people (label 1) is way less than the non-diabetic people (label 0)

In [10]:
diabetes_dataset.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.304200,0.429734,31.190000
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

In [11]:
#separating data and labels

X=diabetes_dataset.drop(columns='Outcome', axis=1) #axis should be specified
Y= diabetes_dataset['Outcome']

if column dropped --> axis = 1
    
if row dropped --> axis = 0

# Data Standaralization

In [14]:
scaler= StandardScaler()

In [15]:
scaler.fit(X)

StandardScaler()

In [17]:
standarized_data = scaler.transform(X)

In [18]:
print(standarized_data)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]

In [21]:
X = standarized_data
Y = diabetes_dataset['Outcome']

In [22]:
print(X,Y)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]] 0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

Train Test Split

In [25]:
X_train, X_test, Y_train, Y_test =  train_test_split(X,Y, test_size = 0.2, stratify = Y, random_state =2)

In [26]:
print(X.shape, Y.shape, X_test.shape)

(768, 8) (768,) (154, 8)

# training the model

In [27]:
classifier = svm.SVC(kernel='linear')

In [28]:
#trainging the support vector Machine Classifieer

classifier.fit(X_train, Y_train)

SVC(kernel='linear')

# Model Evaluation

1- Accuracy Score

In [32]:
# accuracy score on the training data

X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score (X_train_prediction, Y_train)

In [33]:
print('Accuracy score of the training data: ', training_data_accuracy)

Accuracy score of the training data:  0.7866449511400652

In [34]:
# accuracy score on the testing data

X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score (X_test_prediction, Y_test)

In [35]:
print('Accuracy score of the test data: ', test_data_accuracy)

Accuracy score of the test data:  0.7727272727272727

# Making a Predictive System

In [43]:
input_data = (1,88,62,24,44,29.9,0.422,23)

# change input data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

#reshape the array as we are predecting for one instance (only one data point)
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

# standarize the input data
std_data = scaler.transform(input_data_reshaped)

print(std_data)

prediction = classifier.predict(std_data)


# the prediction is a list with only one element
if (prediction[0]==1):
    print ('the person is diabetic')
else :
    print('the person is not diabetic')

[[-0.84488505 -1.02950492 -0.36733675  0.21726125 -0.31084315 -0.26558844
  -0.15063235 -0.87137393]]
the person is not diabetic

/home/chayma/qlstm_env/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

---
---
what if we used Logistic regression
--

In [44]:
from sklearn.linear_model import LogisticRegression

In [45]:
model = LogisticRegression()

In [46]:
model.fit(X_train, Y_train)

LogisticRegression()

# Model Evaluation

In [49]:
#accuracy on training data

X_train_prediction_LR = model.predict(X_train)

training_data_accuracy_LR = accuracy_score(X_train_prediction_LR, Y_train)

In [51]:
print('accuracy on training data : ', training_data_accuracy_LR)

accuracy on training data :  0.7850162866449512

In [52]:
#accuracy on test data
X_test_prediction_LR = model.predict(X_test)
test_data_accuracy_LR = accuracy_score(X_test_prediction_LR, Y_test)

In [53]:
print('accuracy on test data : ', test_data_accuracy_LR)

accuracy on test data :  0.7597402597402597

In [54]:
print('accuracy on test data using svm : ', test_data_accuracy)
print('accuracy on test data using LR : ', test_data_accuracy_LR)

accuracy on test data using svm :  0.7727272727272727
accuracy on test data using LR :  0.7597402597402597

In [55]:
print('accuracy on traint data using svm : ', training_data_accuracy)
print('accuracy on train data using LR : ', training_data_accuracy_LR)

accuracy on traint data using svm :  0.7850162866449512
accuracy on train data using LR :  0.7850162866449512

---

### Why training accuracy is the same

Both models were trained on the **same scaled data**, with the **same split**, and this dataset is relatively simple and low-dimensional (8 features). Both models converge to a very similar decision boundary on the training set, they're both linear classifiers, so on clean, standardized data they can land on the same training accuracy by coincidence.

### Why test accuracy differs

The test set is **unseen data**:

- SVM optimizes for the **maximum margin**, it finds the boundary that is as far as possible from both classes. This makes it **generalize better** to new points.
- LR optimizes for **log-likelihood on the training set**, it fits the training data well, but the boundary isn't necessarily the most "cautious" one.
- SVM only cares about **support vectors** (the hardest points near the boundary). LR is influenced by all 614 training points, including easy ones far from the boundary, which can slightly skew the boundary.

In other words: **SVM's margin maximization is specifically designed to generalize**, which is why it edges ahead on unseen data.